spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false

server:
  port: ${SERVER_PORT}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

app:
  base-url: ${APP_BASE_URL}

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${JWT_EXPIRATION_ACCESS_TOKEN}
    refresh: ${JWT_EXPIRATION_REFRESH_TOKEN}

email:
  from: ${APP_DOMAIN_EMAIL_ADDRESS}
  provider: ${EMAIL_PROVIDER}
  api-key: ${EMAIL_PROVIDER_TOKEN}

async:
  executor:
    core-pool-size: ${ASYNC_THREAD_CORE_POOL_SIZE}
    max-pool-size: ${ASYNC_THREAD_MAX_POOL_SIZE}
    queue-capacity: ${ASYNC_THREAD_QUEUE_CAPACITY}
    keep-alive-seconds: ${ASYNC_THREAD_KEEP_ALIVE_SECONDS}
    thread-name: ${ASYNC_THREAD_NAME}