spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE}

  application:
    name: user-registration-system

app:
  base-url: http://localhost:8080

jwt:
  secret: xSivtQFAQx9ij7qkTaZGxClzFB8mfXaBCuZHpzzmPTD/A0g7vmbi4+RW1yoVztMz
  expiration:
    access: 1
    refresh: 1

email:
  from: noreply@example.com
  provider: test
  api-key: dummy-key

async:
  executor:
    core-pool-size: 2
    max-pool-size: 4
    queue-capacity: 10
    keep-alive-seconds: 30
    thread-name: test-thread
