spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  application:
    name: user-registration-system

app:
  base-url: http://localhost:8080

jwt:
  secret: xSivtQFAQx9ij7qkTaZGxClzFB8mfXaBCuZHpzzmPTD/A0g7vmbi4+RW1yoVztMz
  expiration:
    access: 1
    refresh: 1

email:
  from: noreply@example.com
  provider: test
  api-key: dummy-key

async:
  executor:
    core-pool-size: 2
    max-pool-size: 4
    queue-capacity: 10
    keep-alive-seconds: 30
    thread-name: test-thread
